/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { BooksController } from '../src';
import { testClient } from './testClient';
import { makeApiCall } from './testHelper';

describe('BooksController', () => {
  let controller : BooksController;

  beforeAll(() => {
    controller = new BooksController(testClient);
  });

  it('should Test updateBookCoverById', async () => {
    const bookId = 1;

    const response = await makeApiCall(
      () => controller.updateBookCoverById(bookId, undefined)
    );

    expect(response.statusCode).toBe(200);
  });
});
