/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { NewOrder, OrdersController } from '../src';
import { testClient } from './testClient';
import { expectHeadersToMatch, makeApiCall } from './testHelper';

describe('OrdersController', () => {
  let controller : OrdersController;

  beforeAll(() => {
    controller = new OrdersController(testClient);
  });

  it('should Test createOrder', async () => {
    const body: NewOrder = {
      user: 1,
      products: [
        1,
        3
      ],
    };

    const response = await makeApiCall(
      () => controller.createOrder(body)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });

  it('should Test getOrderStream', async () => {
    const response = await makeApiCall(
      () => controller.getOrderStream()
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['text/event-stream', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
