/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDK } from "../index.js";
import { expect, test } from "vitest";

test("Books Get Book By Id Test Use Case 1", async () => {
    const sdk = new SDK({
        apiKey: process.env["TEST_API_KEY"] ?? "",
    });
    const result = await sdk.books.getBookById({
        bookId: 1,
    });
    expect(result).toBeDefined();
    expect(result).toEqual({
        id: 2,
        title: "The Hobbit",
        description: "A fantasy novel by J.R.R. Tolkien",
        price: 1599,
        category: "Fantasy",
        author: {
            id: 1,
            name: "Robert C. Martin",
            photo: "https://example.com/photos/robert.jpg",
            biography:
                'Robert Cecil Martin, colloquially known as "Uncle Bob", is an American software engineer...',
        },
        coverImage: "https://example.com/covers/cleancode.jpg",
    });
});
