/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface AuthorWithName {
  id?: number;
  name: string;
  photo?: string;
  biography?: string;
}

export const authorWithNameSchema: Schema<AuthorWithName> = object({
  id: ['id', optional(number())],
  name: ['name', string()],
  photo: ['photo', optional(string())],
  biography: ['biography', optional(string())],
});
