/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { CategoryEnum, categoryEnumSchema } from './categoryEnum';
import { Author2, author2Schema } from './containers/author2';

export interface Book {
  id?: number;
  title: string;
  description: string;
  /** Price in USD cents */
  price: number;
  category: CategoryEnum;
  author: Author2;
  coverImage?: string;
}

export const bookSchema: Schema<Book> = object({
  id: ['id', optional(number())],
  title: ['title', string()],
  description: ['description', string()],
  price: ['price', number()],
  category: ['category', categoryEnumSchema],
  author: ['author', author2Schema],
  coverImage: ['cover_image', optional(string())],
});
