/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Order, orderSchema } from './order';

/** A message in the order stream */
export interface OrderStreamMessage {
  id: string;
  event: string;
  data: Order;
}

export const orderStreamMessageSchema: Schema<OrderStreamMessage> = object({
  id: ['id', string()],
  event: ['event', string()],
  data: ['data', lazy(() => orderSchema)],
});
