/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, Schema, string } from '../schema';
import { OrderProducts, orderProductsSchema } from './containers/orderProducts';
import { StatusEnum, statusEnumSchema } from './statusEnum';
import { User, userSchema } from './user';

export interface Order {
  id: number;
  date: string;
  status: StatusEnum;
  user: User;
  products: OrderProducts[];
}

export const orderSchema: Schema<Order> = object({
  id: ['id', number()],
  date: ['date', string()],
  status: ['status', statusEnumSchema],
  user: ['user', lazy(() => userSchema)],
  products: ['products', array(orderProductsSchema)],
});
