/**
 * Bookstore APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { oneOf, Schema, validateAndMap } from '../../schema';
import { FantasyBook, fantasyBookSchema } from '../fantasyBook';
import { ProgrammingBook, programmingBookSchema } from '../programmingBook';
import { SciFiBook, sciFiBookSchema } from '../sciFiBook';

/** This is a container type for one-of types. */
export type OrderProducts = FantasyBook | ProgrammingBook | SciFiBook;

export const orderProductsSchema: Schema<OrderProducts> = oneOf([
  fantasyBookSchema,
  programmingBookSchema,
  sciFiBookSchema,
]);

export namespace OrderProducts {
  /**
   * Validation method to narrow down union type to FantasyBook type case.
   *
   * This is FantasyBook case.
   */
  export function isFantasyBook(value: unknown): value is FantasyBook {
    const validationResult = validateAndMap(value, fantasyBookSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to ProgrammingBook type case.
   *
   * This is ProgrammingBook case.
   */
  export function isProgrammingBook(value: unknown): value is ProgrammingBook {
    const validationResult = validateAndMap(value, programmingBookSchema);
    return validationResult.errors === false;
  }

  /**
   * Validation method to narrow down union type to SciFiBook type case.
   *
   * This is SciFiBook case.
   */
  export function isSciFiBook(value: unknown): value is SciFiBook {
    const validationResult = validateAndMap(value, sciFiBookSchema);
    return validationResult.errors === false;
  }
}
